/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as UsersRegisterImport } from './routes/users/register'
import { Route as UsersLoginImport } from './routes/users/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const UsersRegisterRoute = UsersRegisterImport.update({
  id: '/users/register',
  path: '/users/register',
  getParentRoute: () => rootRoute,
} as any)

const UsersLoginRoute = UsersLoginImport.update({
  id: '/users/login',
  path: '/users/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users/login': {
      id: '/users/login'
      path: '/users/login'
      fullPath: '/users/login'
      preLoaderRoute: typeof UsersLoginImport
      parentRoute: typeof rootRoute
    }
    '/users/register': {
      id: '/users/register'
      path: '/users/register'
      fullPath: '/users/register'
      preLoaderRoute: typeof UsersRegisterImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/login': typeof UsersLoginRoute
  '/users/register': typeof UsersRegisterRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/login': typeof UsersLoginRoute
  '/users/register': typeof UsersRegisterRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users/login': typeof UsersLoginRoute
  '/users/register': typeof UsersRegisterRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/login' | '/users/register' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/login' | '/users/register' | '/users'
  id: '__root__' | '/' | '/users/login' | '/users/register' | '/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersLoginRoute: typeof UsersLoginRoute
  UsersRegisterRoute: typeof UsersRegisterRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersLoginRoute: UsersLoginRoute,
  UsersRegisterRoute: UsersRegisterRoute,
  UsersIndexRoute: UsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users/login",
        "/users/register",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users/login": {
      "filePath": "users/login.tsx"
    },
    "/users/register": {
      "filePath": "users/register.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
